version: '3'

services:
  timetrackerDB:
    container_name: take-order-db
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: take-order
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge