
export default function AllergensPage() {
  return (
    <>
      <section className="Allergens">
        <h1>Etiquetado de sustancias que causan alergias e intolerancias</h1>
        <p>La mayoría de las personas pueden comer una gran variedad de alimentos sin problemas. No obstante, en un pequeño porcentaje de la población determinados alimentos o componentes de los mismos pueden provocar reacciones adversas (alergias e intolerancias alimentarias). Las personas con alergias graves deben ser extremadamente cuidadosas con los alimentos que consumen.</p>
        <p>La mayoría de alergias alimentarias están asociadas al consumo de un grupo reducido de alimentos. Los alérgenos alimenticios más comunes son la leche de vaca, los huevos, la soja, el trigo, los crustáceos, las frutas, los cacahuetes y los frutos secos, como las nueces. Para ellos se han establecido normas de etiquetado que obligan a indicar su presencia cuando se incorporan a los alimentos como ingredientes.</p>
        <p>El <a href="http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2011:304:0018:0063:ES:PDF" target="_blank" title=" enlace externo en nueva ventana ">Reglamento (UE) nº 1169/2011</a> del Parlamento Europeo y del Consejo de 25 de octubre de 2011 sobre la información alimentaria facilitada al consumidor, en su propósito de perseguir un alto nivel de protección de la salud de los consumidores y garantizar su derecho a la información para que los consumidores tomen decisiones con conocimiento de causa, ha venido, entre otros aspectos, a mejorar y clarificar la información alimentaria relativa a sustancias que causan a alergias o intolerancias en los alimentos.</p>
        <p>En los alimentos envasados, la información sobre los alérgenos deberá aparecer en la lista de ingredientes, debiendo destacarse mediante una composición tipográfica que la diferencie claramente del resto de la lista de ingredientes (p. ej., mediante el tipo de letra, estilo o color de fondo). En ausencia de una lista de ingredientes debe incluirse la mención “contiene”, seguida de la sustancia o producto que figura en el anexo II. (Anexo que será reexaminado por la Comisión, teniendo en cuenta los avances científicos y, si procede, actualizará la lista).</p>
        <p>El artículo 44 del Reglamento establece que la información sobre alérgenos también es obligatoria en los alimentos no envasados y deja en manos de los EEMM regular por un lado qué otra información alimentaria (además de la relativa a alérgenos) se facilita en los alimentos no envasados y los medios para facilitarla.</p>
        <p>Como consecuencia, el pasado 4 de marzo (con fecha de entrada en vigor 5 de marzo) se publicó en el BOE el <a href="http://www.boe.es/boe/dias/2015/03/04/pdfs/BOE-A-2015-2293.pdf" target="_blank" title=" enlace externo en nueva ventana "><i>Real Decreto 126/2015, de 27 de febrero,</i></a><i> por el que se aprueba la norma general relativa a la información alimentaria de los alimentos que se presenten sin envasar para la venta al consumidor final y a las colectividades, de los envasados en los lugares de venta a petición del comprador, y de los envasados por los titulares del comercio al por menor.</i>
        </p>
        <p>El Real Decreto 126/2015 tiene un error a lo largo del texto del artículo 6&nbsp; apartado 5, de tal manera que:</p>
        <p>Donde figura “artículo 4.2”</p>
        <p>Debe figurar ”artículo 4.1.b”</p>
        <p>
          <a href="http://www.boe.es/boe/dias/2015/04/11/pdfs/BOE-A-2015-3904.pdf" target="_blank" title=" enlace externo en nueva ventana ">Corrección de errores del Real Decreto 126/2015</a>, de 27 de febrero, por el que se aprueba la norma general relativa a la información alimentaria de los alimentos que se presenten sin envasar para la venta al consumidor final y a las colectividades, de los envasados en los lugares de venta a petición del comprador, y de los envasados por los titulares del comercio al por menor.</p>
        <p>AECOSAN ha elaborado una <a href="/AECOSAN/docs/documentos/seguridad_alimentaria/gestion_riesgos/guia_aplicacion_informacion.pdf">Guía de la aplicación de las exigencias de información alimentaria de los alimentos que se presenten sin envasar para la venta al consumidor final y a las colectividades, de los envasados en los lugares de venta a petición del comprador, y de los envasados por los titulares del comercio al por menor.</a>
        </p>
        <p>El objetivo de esta Guía, basada en parte en el documento <i>Allergen information for loose foods </i>de la <i>Food Standard Agency </i>británica, es ayudar a los operadores de empresas alimentarias y a las autoridades encargadas del control oficial, a entender y aplicar el Real Decreto 126/2015, de 27 de febrero. Sin embargo, no tiene valor jurídico alguno y, en caso de conflicto, la interpretación de la legislación incumbe en última instancia a los Tribunales de Justicia. La presente Guía debe consultarse en relación con el citado Real Decreto y con el Reglamento (UE) Nº 1169/2011, de25 de octubre, sobre la información alimentaria facilitada al consumidor.</p>
        <p>El 13 de julio de 2017 la Comisión Europea adoptó una Notificación sobre la información alimentaria facilitada en relación a las sustancias que causan alergias e intolerancias. Este documento actualiza la guía sobre etiquetado de alérgenos elaborada con arreglo a la Directiva 2000/13/CE. La nueva Notificación tiene como objetivo ayudar a los consumidores, operadores alimentarios y autoridades nacionales a entender los nuevos requisitos del Reglamento (UE) Nº 1169/2011 en relación a la indicación de la presencia de ciertas sustancias o productos que causan alergias o intolerancias. La Notificación ha sido elaborada en colaboración con los Estados miembros y fue objeto de consulta pública.</p>
        <p>La Comunicación fue publicada en el Diario Oficial de la Unión Europea (DOUE) del 13 de diciembre de 2017 y puede consultarse en los enlaces que se muestran a continuación.</p>
        <p>
          <a href="/AECOSAN/docs/documentos/seguridad_alimentaria/gestion_riesgos/comunicacion_alergias_comision.pdf">Comunicación de la Comisión de 13.7.2017 relativa a la información alimentaria facilitada acerca de las sustancias o productos que causan alergias o intolerancias, según figuran en el anexo II del Reglamento (UE) Nº 1169/2011, sobre la información alimentaria facilitada al consumidor.</a>
        </p>
        <p>
          <a href="/AECOSAN/docs/documentos/seguridad_alimentaria/gestion_riesgos/comunicacion_alergias_comision_en.pdf">Commission Notice of 13.7.2017 relating to the provision of information on substances or products causing allergies or intolerances as listed in Annex II of Regulation (EU) Nº 1169/2011 on the provision of food information to consumers.</a>
        </p>
        <p>Dada la relevancia de este tema, en el marco de las actividades de la Agencia Española de Seguridad Alimentaria y Nutrición (AESAN) programadas para el año 2020, se acordó desdoblar el folleto anterior y realizar un folleto divulgativo específico para la “Intolerancia a la lactosa. Información alimentaria”, con objeto de que llegue una información más clara y más fácilmente comprensible para este grupo de población.</p>
        <p>En el folleto, disponible más abajo, se destaca, entre otros, la importancia de leer la lista de ingredientes, prestar atención al etiquetado precautorio, la información sobre la presencia de lactosa en las diferentes modalidades de venta, información alimentaria, en las etiquetas, carteles, venta a distancia, información oral, menú o carta….&nbsp;</p>
      </section>
    </>
  );
}